// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  content?: PortableTextBlock[];
  english_generation_disabled?: boolean;
  english_generation_status?: string;
  english_generation_source_id?: string;
  english_generation_source_slug?: string;
  english_generation_source_version?: string;
  english_generation_note_version?: string;
  english_generation_content_hash?: string;
  english_generation_failure_reason?: string;
  english_generation_gate_results?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteSection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content: PortableTextBlock[];
  links?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    posts: Post;
    site_sections: SiteSection;
  }
}