name = "blog-api"
main = "src/index.ts"
compatibility_date = "2023-01-01"

# 変数の宣言のみ行い、実際の値は.dev.varsまたはシークレットで設定します
[vars]
# 非機密情報はここに直接設定可能
ENVIRONMENT = "development"

# KVストア設定
kv_namespaces = [
    { binding = "BLOG_CACHE", id = "${KV_BLOG_CACHE_ID}", preview_id = "${KV_BLOG_CACHE_PREVIEW_ID}" },
]

# 環境別の設定
[env.development]
# 開発環境用の設定
vars = { ENVIRONMENT = "development" }

[env.production]
# 本番環境用の設定
vars = { ENVIRONMENT = "production" }

[[routes]]
pattern = "api.shuymn.me/*"
zone_name = "shuymn.me"
