name: Deploy to Cloudflare Workers Assets

on:
  push:
    branches: [main]
    paths:
      - 'apps/blog/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run --filter=blog build
      - name: Deploy to Cloudflare Workers
        run: pnpm run --filter=blog deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          KV_BLOG_CACHE_ID: ${{ secrets.KV_BLOG_CACHE_ID }}
          KV_BLOG_CACHE_PREVIEW_ID: ${{ secrets.KV_BLOG_CACHE_PREVIEW_ID }}